name: insurance_policies

on: 
  push:
    branches: [ main ]
    paths:
      - 'schemas/insurance_policies/**'
      - utils/gh-actions/schemas-action-generator.sh
  pull_request:
    paths:
      - 'schemas/insurance_policies/**'
      - utils/gh-actions/schemas-action-generator.sh

jobs:
  lint-insurance_policies:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: korelstar/xmllint-problem-matcher@v1
    - name: Lint Schema & XML
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./schemas/insurance_policies/Insurance_policies.xml
        xml-schema-file: ./schemas/insurance_policies/insurance_policies.xsd
