name: term_deposit

on: 
  push:
    branches: [ main ]
    paths:
      - 'schemas/term_deposit/**'
      - utils/gh-actions/schemas-action-generator.sh
  pull_request:
    paths:
      - 'schemas/term_deposit/**'
      - utils/gh-actions/schemas-action-generator.sh

jobs:
  lint-term_deposit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: korelstar/xmllint-problem-matcher@v1
    - name: Lint Schema & XML
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./schemas/term_deposit/Term_Deposit.xml
        xml-schema-file: ./schemas/term_deposit/term_deposit.xsd
