name: national_pension_system

on: 
  push:
    branches: [ main ]
    paths:
      - 'schemas/national_pension_system/**'
      - utils/gh-actions/schemas-action-generator.sh
  pull_request:
    paths:
      - 'schemas/national_pension_system/**'
      - utils/gh-actions/schemas-action-generator.sh

jobs:
  lint-national_pension_system:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: korelstar/xmllint-problem-matcher@v1
    - name: Lint Schema & XML
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./schemas/national_pension_system/NPS.xml
        xml-schema-file: ./schemas/national_pension_system/nps.xsd
