name: recurring_deposit

on: 
  push:
    branches: [ main ]
    paths:
      - 'schemas/recurring_deposit/**'
      - utils/gh-actions/schemas-action-generator.sh
  pull_request:
    paths:
      - 'schemas/recurring_deposit/**'
      - utils/gh-actions/schemas-action-generator.sh

jobs:
  lint-recurring_deposit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: korelstar/xmllint-problem-matcher@v1
    - name: Lint Schema & XML
      uses: ChristophWurst/xmllint-action@v1
      with:
        xml-file: ./schemas/recurring_deposit/Recurring_deposit.xml
        xml-schema-file: ./schemas/recurring_deposit/recurring_deposit.xsd
